# Docker Configuration
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/organsync_matching
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  redis:
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/organsync
          jwk-set-uri: http://keycloak:8080/auth/realms/organsync/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.organsync.matching: INFO