# PostgreSQL Configuration for Production
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/organsync_matching
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  h2:
    console:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.organsync.matching: INFO
    org.springframework.kafka: WARN
    org.hibernate: WARN

organsync:
  matching:
    algorithm:
      max-cycle-length: 4
      max-chain-length: 10
      timeout-seconds: 60